version: "3.7"

services:
  mysql:
    image: mysql:latest
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: xhuma
      MYSQL_USER: abc
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MYSQL_ALLOW_EMPTY_PASSWORD: root
      MYSQL_RANDOM_ROOT_PASSWORD: root
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    expose:
      - "3306"
